### ISSUE TITLE
How to flash?

### ISSUE THREAD

**Issue by dariotarantini** [MediatekInfo/DZ09#1]
Hi, i ve built the project.
I have theese three files:
`DZ09.bin  DZ09.elf  DZ09.map`
How can i flash them on my device?

**Comment by MediatekInfo** [comment]
Hi, I added firmware utilities and instructions (howto.pdf).

**Comment by dariotarantini** [comment]
uhm, if i want to flash on linux?

**Comment by MediatekInfo** [comment]
Unfortunately, the SoC manufacturer has not taken care of the release of utilities for Linux. For now, the only option is to use a virtual machine.

**Comment by MediatekInfo** [comment]
By the way, compiled binaries must be signed with SHA-1 hash, otherwise ROM-Boot will not run the firmware.
To do this, in the folder "tools" is the utility mk_sign.exe. It is compiled under Windows, but in the near future I will try to put the source code in a separate repository.

**Comment by dariotarantini** [comment]
Can you make a telegram group?

**Comment by MediatekInfo** [comment]
What's the point?

**Comment by dariotarantini** [comment]
create a place where all interested people can enter to exchange information quickly and optimally.

**Comment by MediatekInfo** [comment]
This is a good idea, I will think about it. But now I have very little free time to develop this project.
So far this is just a research project, but rather a set of sources for the MT6261 platform.

**Comment by dariotarantini** [comment]
Okay i just made it, if you want join https://t.me/joinchat/ClmZPBcfY50W23u5Pcq9zg

I dont write a lot of message

**Comment by MediatekInfo** [comment]
Telegram is banned by some Internet providers in Russia, I will try other ways when I get home.

**Comment by dariotarantini** [comment]
Just download the app and get here some proxies

https://t.me/s/ProxyMTProto

**Comment by MediatekInfo** [comment]
Banned in the telegram for a link to the cloud, lol. If you have questions, ask them here.

**Comment by FireTner** [comment]
Could I join the group please? I was banned I assume because you thought I was someone random but I am interested in this project as I dug up DZ09 I got a while ago @dariotarantini

**Comment by joelsours123-spec** [comment]
> Okay i just made it, if you want join https://t.me/joinchat/ClmZPBcfY50W23u5Pcq9zg

Invalid link, could a new one be created if the chat is still active?
<img width="268" height="83" alt="Image" src="https://github.com/user-attachments/assets/009fe48a-dc70-4a45-bc39-b083490271ca" />
