### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ghost** [MediatekInfo/DZ09#3]
Do you mind giving some examples with use of the screen and other important things? I am having a hard time with the code and am pretty new to anything other than Arduino.
Thanks!

**Comment by MediatekInfo** [comment]
The project has not yet been completed at the system level. Now I'm too busy to work on this project, but I really hope to continue soon.

**Comment by Drsaqi7** [comment]
did you extract the firmware file and analyze it to find any vulnerabilites?

**Comment by MediatekInfo** [comment]
I didn't set out to search for vulnerabilities. I just wanted to explore the hardware platform.
