### ISSUE TITLE
how to build

### ISSUE THREAD

**Issue by lidonglei1** [MediatekInfo/DZ09#4]

**Comment by MediatekInfo** [comment]
You can download a newer version of the IDE from the official website https://www.embitz.org or version 1.11 from cloud storage https://disk.yandex.ru/d/bld_TVYbYNQ8-w

**Comment by lidonglei1** [comment]
many thanks.
And the compiler choose ARM GCC Compiler?

**Comment by lidonglei1** [comment]
And how to add the prj into the IDE?
many thanks.

**Comment by lidonglei1** [comment]
Many thanks.
